local menu = require('conmenu.menu')
local javascript = require('conmenu.javascript')

-- hi NormalFloat guifg=Normal gui=bold guibg=#000000
-- hi FloatBorder guifg=#83a598 gui=bold guibg=#000000
return {
  -- User configured
  open = menu.open,
  openCustom = menu.openCustom,
  close = menu.close,

  executeItem = menu.executeItem,
  switchItem = menu.switchItem,

  fromNpm = javascript.fromNpm,
  fromLerna = javascript.fromLerna,

  -- Used by bindings generated by this script
  executeItemNum = menu.executeItemNum,
}
